### ISSUE TITLE
Check if IEnumerable<object> has any values inside without getting IndexOutOfRangeException

### ISSUE THREAD

**Issue by NR-NiMi** [ChrisHodges/LightweightExcelReader#8] opened 2021-04-07 21:44 UTC
Hello I asked the question on stackoverflow and it seems as it is a bug from LightweightExcelReader:
https://stackoverflow.com/questions/66993917/check-if-ienumerableobject-has-any-values-inside-without-getting-indexoutofran/66994213#66994213

**Comment by ChrisHodges** [comment] 2021-04-08 12:40
Hi NR-NiMi and thanks for this. For clarity, the issue is that calling this code:

```csharp
var sheetReader = new ExcelReader("/Path/to/workbook.xlsx")["Sheet1"];
IEnumerable<object> row = sheetReader.Row(500);
if (row.Any()) {
   //do stuff
}
```

 on a spreadsheet *that does not have a 500th row* will throw an `IndexOutOfRangeException` on `row.Any()` rather than on the `sheetReader.Row()` method. I agree that this isn't very intuitive. I've made a change on the next version [(0.1.15-beta)](https://www.nuget.org/packages/LightweightExcelReader/0.1.15-beta) so that an exception will throw immediately on calling the `Row()` method. 
 
If you want to avoid an exception completely you should use the `MaxRow` property of the `SheetReader` object, so the example above becomes:

```csharp
var sheetReader = new ExcelReader("/Path/to/workbook.xlsx")["Sheet1"];
if (sheetReader.MaxRow >= 500) {
  IEnumerable<object> row = sheetReader.Row(500);
  //do stuff, safe in the knowledge that the row exists.
} 

```

**Comment by ChrisHodges** [comment] 2021-04-10 11:51
I'm going to go ahead and close this issue as it appears to be resolved. Feel free to reopen if you feel there's anything outstanding.

**Closed by ChrisHodges** 2021-04-10 11:51 UTC
