### ISSUE TITLE
Read empty Cells

### ISSUE THREAD

**Issue by minhhut** [ChrisHodges/LightweightExcelReader#2] opened 2020-12-01 13:59 UTC
Firstly, thanks for your speed excel reader, I tested it and it's much faster compare to ExcelDataReader.

Currently the sheet reader skips empty cell when read next in row, it make impossible to read the whole Excel table into List<List<object>>. Any reason behind this? Or is it a bug?

I have worked around by calculate the cell's address and read from it.

**Comment by ChrisHodges** [comment] 2020-12-01 14:29
Hi and thanks for getting in touch. This behaviour is by design. When using `ReadNext()` or `ReadNextInRow()` the sheet reader will read the next populated cell, skipping over any null values. You can get the address of the last read cell by using the sheet readers `Address` property.

I've considered adding an optional argument to the constructor that would return null values for cells that lay between 2 populated cells, so if you had a spreadsheet like this:

|   | A  | B  | C  |
|---|---|---|---|
| 1  |  1234 |   | abcd  |

performing `ReadNext()` 3 times would give you the results `1234`, `NULL` and `abcd` for cells A1, B1, and C1. 

The constructor would look something like:

```csharp
var excelReaderFromStream = new ExcelReader(stream, ReadNextBehaviour.ReadAllNulls);
```

where `ReadNextBehaviour` would be a enum defined as:

```csharp
public enum ReadNextBehaviour {
	SkipNulls, //Default behaviour - calling ReadNext() will read the next non-null value,
	ReadNullsOnPopulatedRows, // calling ReadNext() will read the next null or non-null value on the current 
//row but will skip empty rows.
	ReadAllNulls, // calling ReadNext() will read the next non-null cell that is within the 
//used range of the spreadsheet.
}
```

Would this be useful to you?

(P.S. if you are mapping a spreadsheet to an class, you might be interested in LightWeightExcelReaders sister project [ExcelToEnumerable](https://github.com/ChrisHodges/ExcelToEnumerable).)

**Comment by minhhut** [comment] 2020-12-01 20:45
Yes, that's exactly my case which has empty cells in the middle. It would be nice if you could make it configurable. I would suggest something which could be extended more options later:
```C#
var reader = new ExcelReader(stream, options => options.ReadNextBehavior = ReadAllNulls);

// or just simple 
var reader = new ExcelReader(stream);
reader.ReadNextBehavior = ReadAllNulls;
```
Regarding to ExcelToEnumerable, i only need to read raw data so it's not needed, but thanks for the info

**Comment by minhhut** [comment] 2020-12-06 10:48
Hi, just to correct my previous comment, by workaround solution use cell's address, the result is not much different compare to ExcelDataReader. Not sure if reading by ReadNext() and ReadNextInRow() will make different but I will give it a try when the skip empty cell is implemented.

**Comment by ChrisHodges** [comment] 2020-12-06 11:16
Ok great. I'm working on this now, and I'll benchmark it to see how it compares with ExcelDataReader. Are you able to send me a sample of the data you're trying to read? Don't worry if you can't, but it would be useful for benchmarking.

**Comment by minhhut** [comment] 2020-12-06 12:25
In my case i tested with file about 100MB and has 1M rows so performance really critical. I don't think it's helpful for you to test such a big file and wait for minutes to see the result. I found some small files which could be used [Sample files ](https://www.contextures.com/xlsampledata01.html#morefiles)

**Comment by boomaze** [comment] 2021-01-25 04:11
Hi, your app is a life save. and it works on some complicate stuff I need to put in a database. All the spreadsheets load fine, and like i said they are fairly complex, but it all work fine Except on sheet gives me the"Input string is not in the right format" as soon as it hits  **CellValuesDictionart.Add(sheetReader.Address, sheetReader.Value)**, but sheetReader.Address "A1" and Value is 24. It also looks like its trying to convert stuff to doubles when I stack the track. Its a **Dictionary<string,object>**. I'm not getting it . I mean why doesn;t it only happen on one sheet. Its try to parse doubles and I'm not getting why. I mean the other sheets have double??Thanks! and really, your app has been a life saver.

**Comment by ChrisHodges** [comment] 2021-01-25 10:09
Hi Boomaze. Thanks for getting in touch and I'm pleased glad you're finding LightweightExcelReader useful. Are you able to open a separate issue describing the problem (just copy and paste what you've put here) and, ideally, link to a spreadsheet which can reproduce the issue?

**Comment by ChrisHodges** [comment] 2021-02-24 16:14
I've added `ReadNextBehaviour` as part of beta release 0.1.14. Let me know if that's working for you and feel free to close this issue if it's behaving as you expect.

https://github.com/ChrisHodges/LightweightExcelReader/releases/tag/v0.1.14beta

In terms of performance, I ran a bench mark against ExcelDataReader and with a spreadsheet full of empty cells LightweightExcelReader is still faster, but only fractionally. If you only have a few empty cells then LightweightExcelReader is still significantly more performant.

However, I'm pretty sure I can do a couple of refactors to improve performance and hopefully I'll be able to put those in the next release.

**Comment by minhhut** [comment] 2021-03-02 22:22
Hi, with my workaround to access values use addresses, and leave all other cells are null, I could produce the table List<List<object>> for our purpose. And yes, it has a better performance compared to ExcelDataReader. 

I also test your beta version but I found a bug already. See my PR.

**Comment by ChrisHodges** [comment] 2021-03-10 14:40
Ok, thanks, I'll check out the PR. I'm going to go ahead and close this issue since the bug you mentioned in the most recent comment relates to localisation and testing.

**Closed** 2021-03-10 14:40 UTC
